"# Stock Data Analyzer" 
"import pandas as pd" 
"import yfinance as yf" 
"from datetime import datetime, timedelta" 
"" 
"def fetch_stock_data(symbol, period='6mo'):" 
"    \"\"\"Fetch stock data from Yahoo Finance\"\"\"" 
"    try:" 
"        stock = yf.Ticker(symbol)" 
"        data = stock.history(period=period)" 
"        return data" 
"    except Exception as e:" 
"        print(f\"Error fetching data for {symbol}: {e}\")" 
"        return None" 
"" 
"def calculate_sma(data, window=20):" 
"    \"\"\"Calculate Simple Moving Average\"\"\"" 
"    return data['Close'].rolling(window=window).mean()" 
"" 
"if __name__ == \"__main__\":" 
"    print(\"Stock Analyzer - Testing Data Fetch\")" 
"    " 
"    # Test with Apple stock" 
"    aapl_data = fetch_stock_data('AAPL')" 
"    if aapl_data is not None:" 
"        print(f\"Fetched {len(aapl_data)} days of AAPL data\")" 
"        print(f\"Latest price: ${aapl_data['Close'].iloc[-1]:.2f}\")" 
"    else:" 
"        print(\"Failed to fetch AAPL data\")" 
